config/routes.rb
Rails.application.routes.draw do
  get 'blogs' => 'home#index', as:'blogs'
  get 'blogs/new' => 'home#new', as:'new_form'
  post 'blogs' => 'home#create'
  get 'blogs/:id' => 'home#show', as:'blog'
  get 'blogs/:id/edit' => 'home#edit', as: 'edit_form'
  patch 'blogs/:id' => 'home#update'
  delete 'blogs/:id' => 'home#destroy', as: 'delete_form'
root 'blog#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @blogs = Blog.all
    end

    def show
        @blog = Blog.find(params[:id])
    end

    def new
        @blog = Blog.new
    end

    def create
        @blog = Blog.create(form_params)
        if @blog.valid?
            redirect_to blogs_path
        end
    end

    def destroy
        @blog = Blog.find(params[:id])
        if @blog.destroy
            redirect_to blogs_path
        end
    end

    def edit 
        @blog = Blog.find(params[:id])
    end
    
    def update
        @blog = Blog.find(params[:id])
        @blog.update(form_params)
    end


    private
    def form_params
        params.require(:blog).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/edit.html.erb
<h1>Edit your Post </h1>

<%= form_with model: @blog, method: :patch do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <br/>
    <%= form.label :content %>
    <%= form.text_area :content %>
    <br/>
    <%= form.submit 'Edit Post'%>
<% end %>

<br/>

<p>
    Back to <%= link_to 'Blog Posts', blogs_path %>
</p>

app/views/home/index.html.erb
<h1> Moesha's Diary </h1>

<ul>
    <% @blogs.each do |blog| %>
        <li> <%= link_to blog.title, blog_path(blog) %> </li>
    <% end %>
</ul>

<br/>

<%= link_to 'Add a new Blog Post', new_form_path %>

app/views/home/new.html.erb
<h3>Create a new Blog Post </h3>

<%= form_with model: @blog do |form| %>
    <%= form.label :title %>
    <%= form.text_field :title %>
    <br/>
    <%= form.label :content %>
    <%= form.text_area :content %>
    <br/>
    <%= form.submit %>
<% end %>

<br/>

<p>
    Back to <%= link_to 'Blog Posts', blogs_path %>
</p>

app/views/home/show.html.erb
<h1> <%= @blog.title %> </h1>

<p>
    <%= @blog.content %>
</p>

<br/>

<p> 
    <%= link_to 'Edit Posts', edit_form_path %> 
</p>

<p>
    <%= button_to 'Delete Posts', delete_form_path, method: :delete %>
</p>

<p>
    Back to <%= link_to 'Blog Posts', blogs_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPostChallenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>